using System;
using System.IO;
using UnityEditor;
using UnityEditor.UIElements;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UIElements;

namespace Cookie.InputWrapper
{
    internal class InputWrapperSettings : ScriptableObject
    {
        private const string ProjectSettingsPath = "Project/Input Wrapper";
        private const string Label = "Input Wrapper";
        private const string Name = "Settings.asset";
        private const string Folder = "Assets/Settings/InputWrapper";
        private static readonly string[] Keywords = { "input", "actions", "wrapper" };

        [SerializeField] [Tooltip("The namespace for the wrapper classes. Leave empty for no namespace")]
        internal string @namespace = "Cookie.InputWrapper";

        [SerializeField]
        [Tooltip(
            "The folder to put the generated wrapper classes in relative to Assets." +
            "\nNOTE: If it's in an assembly definition, it must have a reference to all the C# classes generated by the input system"
        )]
        internal string folder = "Settings/InputSystem/Wrappers";

        [SerializeField]
        [Tooltip(
            "Whether to always include the action map in the action property names. If false, it's only included when multiple maps share the same action name"
        )]
        internal bool alwaysIncludeMap = false;

        [SerializeField] [Tooltip("The assets to generate the wrapper classes for")]
        internal ActionsAsset[] assets;

        [SettingsProvider]
        public static SettingsProvider ProvideSettings() {
            InputWrapperSettings target = GetInst();

            SettingsProvider provider = new(ProjectSettingsPath, SettingsScope.Project, Keywords) {
                label = Label,
                activateHandler = (_, rootElement) => {
                    Label titleLabel = new(Label) {
                        style = {
                            fontSize = 18,
                            paddingLeft = 16,
                            paddingTop = 2,
                            unityFontStyleAndWeight = FontStyle.Bold,
                        },
                    };
                    rootElement.Add(titleLabel);

                    InspectorElement inspector = new(target);

                    PropertyField scriptField = inspector.Query<PropertyField>()
                        .Where(f => f.bindingPath == "m_Script")
                        .First();
                    scriptField?.parent?.Remove(scriptField);

                    rootElement.Add(inspector);
                },
            };

            return provider;
        }

        internal static InputWrapperSettings GetInst() {
            string path = $"{Folder}/{Name}";

            if (AssetDatabase.AssetPathExists(path)) return AssetDatabase.LoadAssetAtPath<InputWrapperSettings>(path);

            if (!Directory.Exists(Folder)) Directory.CreateDirectory(Folder);

            var settings = CreateInstance<InputWrapperSettings>();
            AssetDatabase.CreateAsset(settings, path);
            AssetDatabase.SaveAssets();

            return settings;
        }

        [Serializable]
        internal class ActionsAsset
        {
            [SerializeField] [Tooltip("The class name for the generated wrapper")]
            internal string className = "Actions";

            [SerializeField] [Tooltip("The class name of the C# class generated by the input system")]
            internal string generatedName = "InputSystem_Actions";

            [SerializeField] [Tooltip("The namespace of the C# class generated by the input system")]
            internal string generatedNamespace = "";

            [SerializeField]
            [Tooltip(
                "The input actions asset to generate the wrapper for. NOTE: Must have 'Generate C# Class' enabled"
            )]
            internal InputActionAsset asset;
        }
    }
}