using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.UIElements;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UIElements;

namespace Cookie.InputWrapper
{
    internal class InputWrapperSettings : ScriptableObject
    {
        private const string ProjectSettingsPath = "Project/Input Wrapper";
        private const string Label = "Input Wrapper";
        private static readonly string[] Keywords = { "input", "actions", "wrapper" };
        private static readonly string[] SplitFilePath = { "Settings", "InputWrapper", "Settings.asset" };

        [SerializeField] [Tooltip("The namespace for the wrapper classes. Leave empty for no namespace")]
        internal string @namespace = "Cookie.InputWrapper";

        [SerializeField]
        [Tooltip(
            "The directory to put the generated wrapper classes in relative to Assets.\nNOTE: If it's in an assembly definition, it must have a reference to all the C# classes generated by the input system"
        )]
        internal string directory = "Settings/InputSystem/Wrappers";

        [SerializeField] [Tooltip("The assets to generate the wrapper classes for")]
        internal ActionsAsset[] assets;

        [SettingsProvider]
        public static SettingsProvider ProvideSettings() {
            InputWrapperSettings target = GetInst();

            SettingsProvider provider = new(ProjectSettingsPath, SettingsScope.Project, Keywords) {
                label = Label,
                activateHandler = (_, rootElement) => {
                    Label titleLabel = new(Label) {
                        style = {
                            fontSize = 18,
                            paddingLeft = 16,
                            paddingTop = 2,
                            unityFontStyleAndWeight = FontStyle.Bold,
                        },
                    };
                    rootElement.Add(titleLabel);

                    InspectorElement inspector = new(target);

                    PropertyField scriptField = inspector.Query<PropertyField>()
                        .Where(f => f.bindingPath == "m_Script")
                        .First();
                    scriptField?.parent?.Remove(scriptField);

                    rootElement.Add(inspector);
                },
            };

            return provider;
        }

        internal static InputWrapperSettings GetInst() {
            string path = SplitFilePath.Aggregate("Assets", (current, s) => Path.Join(current, s));

            if (AssetDatabase.AssetPathExists(path)) return AssetDatabase.LoadAssetAtPath<InputWrapperSettings>(path);

            string createdPath = "Assets";
            foreach (string s in SplitFilePath) {
                if (s.Contains(".asset")) break;

                string joinedPath = Path.Join(createdPath, s);
                if (!AssetDatabase.AssetPathExists(joinedPath)) AssetDatabase.CreateFolder(createdPath, s);

                createdPath = joinedPath;
            }

            var settings = CreateInstance<InputWrapperSettings>();
            AssetDatabase.CreateAsset(settings, path);
            AssetDatabase.SaveAssets();

            return settings;
        }

        [Serializable]
        internal class ActionsAsset
        {
            [SerializeField] [Tooltip("The class name for the generated wrapper")]
            internal string className = "Actions";

            [SerializeField]
            [InspectorName("Generated C# Class Name")]
            [Tooltip("The class name of the C# class generated by the input system")]
            internal string generatedCSharpClassName = "InputSystem_Actions";

            [SerializeField]
            [InspectorName("Generated C# Class Namespace")]
            [Tooltip("The namespace of the C# class generated by the input system")]
            internal string generatedCSharpClassNamespace = "";

            [SerializeField]
            [Tooltip(
                "The input actions asset to generate the wrapper for. NOTE: Must have 'Generate C# Class' enabled"
            )]
            internal InputActionAsset asset;
        }
    }
}